spring:
#  velocity:
#    charSet: UTF-8
#    properties:
#      input:
#        encoding: UTF-8
#    output:
#      encoding: UTF-8
  datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    properties:
      hibernate.format_sql: true
      hibernate.tool.hbm2ddl: trace
    show-sql: true
    hibertnate.ddl-auto: create-drop
  h2:
    console:
      enabled: true